SuperGoodSoft/solidus_taxjar

- lib/super_good/solidus_taxjar/tax_calculator.rb
- lib/super_good/solidus_taxjar/version.rb
- spec/super_good/solidus_taxjar/tax_calculator_spec.rb
Solidus has deprecated the `empty?` method on https://github.com/solidusio/solidus/pull/1686 . 
This adds a private `incomplete_address?` method for avoid future problems and remove the deprecation warning in projects that uses this gem.
> Add incomplete_address? check method

- CHANGELOG.md
- lib/super_good/solidus_taxjar/tax_calculator.rb
- lib/super_good/solidus_taxjar/version.rb
- spec/super_good/solidus_taxjar/tax_calculator_spec.rb
From Solidus [Documentation](https://guides.solidus.io/developers/taxation/overview.html#use-code-spree-taxlocation-code-as-the-tax-address): 
> An order's tax_address can – through duck typing  – be a Spree::TaxLocation instead of the shipping address.
This adds a guard clause that validates if the tax_address is a TaxLocation, in this case we know that the address is incomplete.
> Add guard clause for TaxLocation addresses

- spec/super_good/solidus_taxjar/tax_calculator_spec.rb
When an order doesn't have a tax_address, it will rely on the order's
store to build a "TaxAddress" for use as the "tax address which in an
ideal world would be much more address-like... but unfortunately it's
not.
> Add test that covers behaviour with TaxLocation

- CHANGELOG.md
- lib/super_good/solidus_taxjar.rb
- lib/super_good/solidus_taxjar/api_params.rb
Necessary if you need to factor in order level adjustments (boooooo)
into your shipping amounts to make things add up correctly.
> Make shipping amount calculator configurable

- CHANGELOG.md
- lib/super_good/solidus_taxjar/api_params.rb
- spec/super_good/solidus_taxjar/api_params_spec.rb
If an order is adjusted to zero, we don't want to subtract the tax from
it... because that don't make no sense.
A better solution that properly factors in order level adjustments will
be coming eventually, this is just a hack to process some orders
immediately.
> Avoid sending negative order totals

- README.md
Updated the docs to reflect a moving of the error handler configuration from `SuperGood::SolidusTaxJar::TaxCalculator.exception_handler` to `SuperGood::SolidusTaxJar.exception_handler`
https://github.com/SuperGoodSoft/solidus_taxjar/blob/master/CHANGELOG.md#v050
> Fixed the example of the error handler configuration

- .travis.yml
- CHANGELOG.md
- README.md
- lib/super_good/solidus_taxjar.rb
- lib/super_good/solidus_taxjar/api.rb
- lib/super_good/solidus_taxjar/api_params.rb
- lib/super_good/solidus_taxjar/calculator_helper.rb
- lib/super_good/solidus_taxjar/tax_calculator.rb
- lib/super_good/solidus_taxjar/tax_rate_calculator.rb
- spec/super_good/solidus_taxjar/api_params_spec.rb
- spec/super_good/solidus_taxjar/api_spec.rb
- spec/super_good/solidus_taxjar/tax_rate_calculator_spec.rb
This PR adds the new tax rate calculator, based on the same low-level API endpoint as the existing tax calculator. 
According to TaxJar support, the best option to calculate live tax rate for a given address is by using the `/v2/taxes` endpoint.
Also, the readme has been updated with a brief description of the tax calculator and the new tax rate calculator.
> Add tax rate calculator

- CHANGELOG.md
- lib/super_good/solidus_taxjar/calculator_helper.rb
- spec/super_good/solidus_taxjar/tax_rate_calculator_spec.rb
When validating addresses, it may happen that the address has no country, so trying to fetch the country ISO raises an unnecessary error. Using ruby safe navigation prevents this to happen. 
Of course, the address will still result invalid eventually.
This has the extra benefit of avoiding unnecessary error reports to services such as Honeybadger.
> Remove unnecessary errors when validating address without country

- lib/super_good/solidus_taxjar/api_params.rb
`APIParams#order_params` should use the `shipping_calculator` lambda instead of a hardcoded value for providing shipping costs to TaxJar.
> Use shipping_calculator lambda for order shipping param

- lib/super_good/solidus_taxjar/addresses.rb
- spec/super_good/solidus_taxjar/addresses_spec.rb
According to [the documentation](https://developers.taxjar.com/api/reference/#post-validate-an-address), and some testing, the API will raise a `Taxjar::Error::NotFound` error if the API finds no addresses. 
Instead of raising this error to others, we should handle it ourselves and return nil/an empty array like we originally intended.
> Fix handling of no results for address validation

- bin/sandbox
Without this update, the following would fail:
$ bundle exec rake sandbox
> Update extension name

- CHANGELOG.md
- lib/super_good/solidus_taxjar/api.rb
- spec/super_good/solidus_taxjar/api_spec.rb
This is the first pull request to get this extension ready for certification with TaxJar (there will be an issue/milestone to track this process in the future).
TaxJar requires certified extensions to include an API version in the header of each request.
Closes #33.
> Include API version in request headers

- CHANGELOG.md
- lib/super_good-solidus_taxjar.rb
- lib/super_good/engine.rb
In order to have the this extension certified by Taxjar, we will need to add significant UI to the solidus backend.
A prerequisite to this is adding a rails engine for Taxjar so components like controllers can be added to the extension and loaded by solidus.
> Add taxjar rails engine

- lib/super_good/solidus_taxjar/api.rb
- spec/super_good/solidus_taxjar/api_spec.rb
To meet Taxjar's certification requirements, we need to supply a 'plugin'
name in each API request header. As such we add this header where the
API version header is supplied.
Closes #35.
> Put plugin name in API request headers

- lib/super_good/engine.rb
---
Once we add an install generator with migrations, having an engine name with a dash in it will cause the migration generation to fail, as migrations will be created with the engine name in it, and dashes are not allowed.
> Update the engine name

- .travis.yml
- CHANGELOG.md
- README.md
- lib/super_good/solidus_taxjar.rb
- lib/super_good/solidus_taxjar/addresses.rb
- lib/super_good/solidus_taxjar/api.rb
- lib/super_good/solidus_taxjar/api_params.rb
- lib/super_good/solidus_taxjar/calculator_helper.rb
- lib/super_good/solidus_taxjar/discount_calculator.rb
- lib/super_good/solidus_taxjar/tax_calculator.rb
- lib/super_good/solidus_taxjar/tax_rate_calculator.rb
- lib/super_good/solidus_taxjar/version.rb
- spec/super_good/solidus_taxjar/addresses_spec.rb
- spec/super_good/solidus_taxjar/api_params_spec.rb
- spec/super_good/solidus_taxjar/api_spec.rb
- spec/super_good/solidus_taxjar/discount_calculator_spec.rb
- spec/super_good/solidus_taxjar/tax_calculator_spec.rb
- spec/super_good/solidus_taxjar/tax_rate_calculator_spec.rb
- spec/super_good/solidus_taxjar_spec.rb
- super_good-solidus_taxjar.gemspec
---
Support loading this extension with the zeitwork loader
This is a breaking change due the renaming of the module
---
1. Set up this gem in a rails project that uses zeitwork
---
> Support zeitwerk loading (0.18.0)

- CHANGELOG.md
- lib/super_good/solidus_taxjar/api_params.rb
- spec/super_good/solidus_taxjar/api_params_spec.rb
---
Fixes a typo in the helper method which transforms a `Spree::Address` into the payload parameters we send to TaxJar.
---
1. Use an order with an address without a `state` association, but with a `state_name` instead.
---
> Fix typo in address parameter helper

- CHANGELOG.md
- lib/super_good/solidus_taxjar/api.rb
- spec/super_good/solidus_taxjar/api_spec.rb
---
In #34, we modified `.default_taxjar_client` to include the API version,
and then the name of the plugin, but we also introduced a critical bug.
`Taxjar::Client#set_api_config` returns a hash and not the TaxJar
client, so it is not safe to chain the method call. As such, we add a
spec to cover this case and patch the class method.
---
1. Setup a sandbox store `bin/rails-sandbox server`
2. Setup the store to use this gem as the default tax calculator
3. Checkout from the store and verify you see taxes on the page
---
> Fix critical bug in API class

- CHANGELOG.md
- lib/super_good/solidus_taxjar/api.rb
- spec/super_good/solidus_taxjar/api_spec.rb
---
Add an API call needed by myself and @Noah-Silvera to implement #42, and to support #32
---
1. Open a rails console.
2. Call the `nexus_regions` method manually and verify it behaves as you expect.
---
> Add TaxJar `nexus_regions` API call

- CHANGELOG.md
- lib/super_good/solidus_taxjar.rb
- spec/super_good/solidus_taxjar/api_params_spec.rb
- spec/super_good/solidus_taxjar_spec.rb
---
The current default shipping calculator did not consider promotions when calculating shipping.
---
1. Create a shipment
2. Add a promotion to the shipment to reduce it's cost
3. Ensure the shipment cost on the checkout screen takes the promotion into account
---
Screenshots
---
> Take adjustments into account when calculating shipping

- .circleci/config.yml
- CHANGELOG.md
- Gemfile
---
ExecJS released a minor version update with a breaking change. We want to lock to the previous version (2.7) for now until a fix is released.
https://github.com/rails/execjs/issues/99
---
> Lock ExecJS and solidus extensions orb version

- README.md
---
These instructions were added pre-emptively - currently no migrations or install generators exist.
---
~~- [ ] Update the changelog~~ not necessary because no code changes
> Remove install generator instructions from readme

- CHANGELOG.md
- app/controllers/spree/admin/taxjar_settings_controller.rb
- app/overrides/spree/admin/shared/_configuration_menu.rb
- app/views/spree/admin/taxjar_settings/show.html.erb
- config/routes.rb
- spec/features/spree/admin/taxjar_settings_spec.rb
- spec/spec_helper.rb
- spec/super_good/solidus_taxjar/api_spec.rb
This commit adds a tab to the taxes section of the solidus admin settings. 
This provides the foundation for further configuration of Taxjar through the solidus admin.
Right now, the new settings tab does not display any content.
If the API key is not set, the settings tab should just show a descriptive message asking you to provide an API token. This is to conform with the Taxjar certification checklist requirement to hide the Taxjar settings until an API token is provided.
The descriptive messaging also provides links to signup for Taxjar, and a link to help article for acquiring an API token, to comply with certification requirements. 
Manual Tests
----
1. Set a taxjar API key
1. Don't set a taxjar API key
---
Screenshots
---
> Add basic UI for Taxjar settings in solidus admin

- CHANGELOG.md
- lib/super_good/solidus_taxjar/api_params.rb
- spec/super_good/solidus_taxjar/api_params_spec.rb
---
The taxjar validation API has the option to take a freeform street input consisting of the full address. This means that if both address1 and address2 exist, we should concatenate them and pass them to the street parameter.
This can help with situations that involve a ZIP+4 code in the US for example. A user may enter their 5 digit zip code in the zip code field, but enter their ZIP+4 code in the address2 field.
---
1. Manually call this API with a valid taxjar key and the situation described above with a ZIP+4 code. Ensure the address is validated correctly with the ZIP+4 code in the freeform input taken into account
---
> Use spree address2 if it is present

- CHANGELOG.md
- super_good-solidus_taxjar.gemspec
---
This PR removes Ruby version upper limit in gemspec to make the gem work with Ruby 3.0.
0.17 version already worked correctly with Ruby 3, but https://github.com/SuperGoodSoft/solidus_taxjar/pull/21 introduced the new restriction.
---
>  Relax Ruby required version to support Ruby 3.0+

- CHANGELOG.md
- Gemfile
---
A new release of ExecJS (2.8.1) patched a bug which was preventing the app from booting, and autoprefixer, which indirectly requires ExecJS for this app, temporarily locked ExecJS to a working version until  they fix a bug, so we no longer have to lock ExecJS ourselves.
---
> Unlock the ExecJS version

- CHANGELOG.md
- README.md
- app/decorators/super_good/solidus_taxjar/spree/order_updater/fire_recalculated_event.rb
- lib/super_good/engine.rb
- lib/super_good/solidus_taxjar/addresses.rb
- lib/super_good/solidus_taxjar/calculator_helper.rb
- lib/super_good/solidus_taxjar/tax_calculator.rb
- spec/models/spree/order_updater_spec.rb
---
Support order_recalculated event in Solidus < 2.11
---
1. Load the sandbox app
---
> Support order_recalculated event in Solidus < 2.11

- CHANGELOG.md
- app/decorators/super_good/solidus_taxjar/spree/shipment/fire_shipment_shipped_event.rb
- spec/models/spree/shipment_spec.rb
---
An an event for when any shipment ships. Orders need to be pushed to TaxJar whenever any part of the order is shipped, so we hook into solidus to add a new event to support this. 
---
> #77 Add shipment shipped event

- CHANGELOG.md
- README.md
- bin/sandbox
- lib/generators/super_good/solidus_taxjar/install_generator.rb
---
Prior to this commit, users were required to manually configure this
extension after installing the gem. We add an install generator so users
can run a single command to handle this.
We include this command in the sandbox script so the sandbox is
ready to use this extension by default.
---
- Create a fresh sandbox app
- Verify it uses this tax calculator by default and generates `sandbox/config/initializers/solidus.rb`
---
> Add install generator

- CHANGELOG.md
- lib/super_good/solidus_taxjar/calculator_helper.rb
- spec/super_good/solidus_taxjar/calculator_helper_spec.rb
---
According to the TaxJar API, the `to_state` field is only required for
CA or US addresses. Right now, we consider an address incomplete if it
does not have a state, which breaks calculation of EU taxes as it is
commonplace to not have a "state"-equivalent.
We should change the incomplete check to only require the state if
TaxJar requires it for that country. This will allow calculation of tax
for EU addresses.
---
Use an EU address with no "state", ensure taxes are still calculated.
---
> Only require state for Canada and US addresses

- CHANGELOG.md
- lib/super_good/solidus_taxjar.rb
- lib/super_good/solidus_taxjar/api.rb
- lib/super_good/solidus_taxjar/api_params.rb
- lib/super_good/solidus_taxjar/transaction_id_generator.rb
- spec/super_good/solidus_taxjar/api_params_spec.rb
- spec/super_good/solidus_taxjar/api_spec.rb
- spec/super_good/solidus_taxjar/transaction_id_generator_spec.rb
---
Finishes #94 
Introduce a utility class for generating `transaction_id`s for transactions
created using the TaxJar reporting API.
This is a step towards implementing a way to update transactions on TaxJar after
they have been updated in Solidus. The recommended way to reflect changes is to
cancel the original transaction and create a new one while referencing the old
one. However TaxJar does not have a way to associate two transactions in any way
so we will be using a suffix appended to the original order number and increment
that every time we cancel and re-create a transaction because the Solidus order
changed. This utility will aid in genrating a new `transaction_id` based on the
current one in TaxJar.
How do you manually test these changes? (if …
> TaxJar Reporting | Transaction ID generator

- CHANGELOG.md
- README.md
- lib/super_good/solidus_taxjar.rb
- spec/super_good/solidus_taxjar_spec.rb
Closes #99.
---
We want to allow end users to be able to turn the TaxJar reporting functionality of this extension on or off.
While the feature is in development, we want reporting to be disabled by default.
---
Not applicable.
---
Screenshots
---
Not applicable.
> Add `reporting_enabled` configuration option

- CHANGELOG.md
- lib/super_good/solidus_taxjar/api.rb
- lib/super_good/solidus_taxjar/api_params.rb
- spec/super_good/solidus_taxjar/api_params_spec.rb
- spec/super_good/solidus_taxjar/api_spec.rb
---
Support submitting refund transactions to TaxJar.
---
1. Open a console on the dummy app
2. Manually call `create_refund_transaction_for` (this extension will call this method in the future, but not yet)
---
> Add new refund transaction endpoint

- CHANGELOG.md
- lib/super_good/solidus_taxjar/api_params.rb
- spec/super_good/solidus_taxjar/api_params_spec.rb
It helps with TaxJars reporting tools to have a human readable
name for the object. TaxJar uses the "description" field for this
purpose.
Here's a screenshot of the different this makes. In the transaction details screen, the top item was created with the "description" field, and the bottom one was not.
Manual Tests
---
---
> Add description to transaction line item params

- CHANGELOG.md
- bin/rails-engine
---
The rails-engine binstub was pointing to the wrong entry point for the extension engine, so it couldn't be used to run various commands, such as generating migrations.
---
---
> Point rails engine binstub at correct entry point

- CHANGELOG.md
- app/decorators/super_good/solidus_taxjar/spree/order_decorator.rb
- app/models/super_good/solidus_taxjar/order_transaction.rb
- db/migrate/20210908205201_create_taxjar_order_transactions.rb
- lib/generators/super_good/solidus_taxjar/install_generator.rb
- lib/super_good/solidus_taxjar.rb
- spec/super_good/solidus_taxjar_spec.rb
---
Orders can be associated with multiple taxjar transactions, so we should add a new model to keep track of this relationship. 
---
1. Create a new `SuperGood::SolidusTaxjar::OrderTransaction` model
---
This ticket is the first step to completing #101.
> Add Taxjar transaction Model

- CHANGELOG.md
- app/models/super_good/solidus_taxjar/refund_transaction.rb
- db/migrate/20211008175113_create_taxjar_refund_transaction.rb
---
Refund transactions are all associated with order transactions, and we want to keep track of their relationship. We also need to keep track of whether a refund for a order transaction has been pushed to taxjar yet.
---
1. Create a refund transaction
---
> Add refund transaction model

- CHANGELOG.md
- app/models/super_good/solidus_taxjar/order_transaction.rb
- lib/super_good/solidus_taxjar/api.rb
- lib/super_good/solidus_taxjar/testing_support/factories/order_transaction_factory.rb
- spec/models/super_good/solidus_taxjar/order_transaction_spec.rb
- spec/spec_helper.rb
- spec/super_good/solidus_taxjar/api_spec.rb
---
This change creates a new record with the `transaction_id` reference used to identify the Solidus order on TaxJar when we create a transaction for it through the reporting API. This is necessary in order for us to be able to fetch and update the transaction in the future, especially in the case when there are multiple transactions for the same Solidus order (due to refund and updates) where the `order.number` does not correspond to the `transaction_id` on TaxJar.
---
1. Create a transaction for a Solidus order using the `Api.create_transaction_for(order)` method
---
Relates to #101
> Save `OrderTransaction` after API call to TaxJar

- CHANGELOG.md
- app/subscribers/super_good/solidus_taxjar/spree/reporting_subscriber.rb
- lib/super_good/engine.rb
- lib/super_good/solidus_taxjar.rb
- lib/super_good/solidus_taxjar/reporting.rb
- spec/subscribers/super_good/solidus_taxjar/spree/reporting_subscriber_spec.rb
- spec/super_good/solidus_taxjar/reporting_spec.rb
- spec/super_good/solidus_taxjar_spec.rb
---
When a shipment is shipped, if there is no transaction for that order, we create a new transaction. The second half of this issue will be completed in https://github.com/SuperGoodSoft/solidus_taxjar/issues/92
---
1. Generate a sandbox app
2. Mark a shipment as shipped
---
Screenshots
---
> Create new transaction when shipped

- .circleci/config.yml
- CHANGELOG.md
---
This moves us in the direction of only testing against major solidus versions. This will unblock existing merges into master while we work on solidus 3.0 and 3.1 support so we can enable the appropriate tests #135 
---
- ~[ ] Run the manual tests~
- ~[ ] Run a sandbox app and verify taxes are being calculated~
> Run CI build against solidus v2.11

- .circleci/config.yml
- CHANGELOG.md
- Gemfile
- spec/subscribers/super_good/solidus_taxjar/spree/reporting_subscriber_spec.rb
- spec/super_good/solidus_taxjar/addresses_spec.rb
- spec/super_good/solidus_taxjar/api_params_spec.rb
- spec/super_good/solidus_taxjar/calculator_helper_spec.rb
- spec/super_good/solidus_taxjar/tax_calculator_spec.rb
- spec/super_good/solidus_taxjar/tax_rate_calculator_spec.rb
- super_good-solidus_taxjar.gemspec
---
This removes the lock we have on the Solidus extensions Orb version
which previous to this commit was running test only on "older" versions
of Solidus which were 2.9 and 2.10. With this change to the Orb version
as well as the switch to the "run-tests" command we will be running tests
against master, 3.1, 3.0 and 2.11 which are the officially supported versions
of Solidus currently.
---
1. Create a PR
---
> Run CI build against current versions of Solidus

- .circleci/config.yml
---
Prior to this commit, each pull request would be run against three
versions of solidus: master, current, and older. While it is good to
stay up to date, master can change quite frequently, so we don't want to
run against master on each branch. Future commits may consider a cron
schedule for running against master.
> Run specs against solidus current and older

- .circleci/config.yml
---
Now that previous commits have removed Solidus master from our main CI
workflow, we define a second workflow to run against Solidus master.
This workflow should be marked as optional to avoid blocking open pull
requests.
> Add workflow to run against Solidus master

- CHANGELOG.md
- lib/super_good/solidus_taxjar/api.rb
- lib/super_good/solidus_taxjar/reporting.rb
- spec/super_good/solidus_taxjar/api_spec.rb
- spec/super_good/solidus_taxjar/reporting_spec.rb
---
**Stop errorring out when an order without `OrderTransaction`s is marked as shipped.**
If Solidus TaxJar's reporting functionality is enabled, and an order is shipped, the `Solidus::Event#shipment_shipped` event that fires causes an error. This is because we were not rescuing from the `StandardError` that notified end users that a reporting feature had not yet been implemented.
This error was unexpected and not handled gracefully. Until the reporting functionality has been completed, we want the `#shipment_shipped` event to *do nothing* if it hits an unimplemented feature's codepath.
---
1. In the Solidus admin, mark an order as shipped.
---
> Handle unimplemented reporting features

- CHANGELOG.md
- app/jobs/super_good/solidus_taxjar/report_transaction_job.rb
- app/subscribers/super_good/solidus_taxjar/spree/reporting_subscriber.rb
- lib/super_good/solidus_taxjar.rb
- spec/jobs/super_good/solidus_taxjar/report_transaction_job_spec.rb
- spec/subscribers/super_good/solidus_taxjar/spree/reporting_subscriber_spec.rb
- spec/super_good/solidus_taxjar_spec.rb
---
To move the reporting of transactions to be performed asynchronously. Previous to this change, when a shipment was shipped, a new reporting transaction was created through API synchronously. This was not ideal because any errors would impact the transition of the shipment to `shipment_shipped`. We have an introduced an Active Job class for reporting, which can be used from other places as well.
---
1. Create an order and mark a shipment as shipped
2. Perform the job 
---
Screenshots
---
> Report transaction asynchronously

- CHANGELOG.md
- PULL_REQUEST_TEMPLATE.md
- spec/features/spree/admin/checkout_spec.rb
- spec/fixtures/cassettes/features/spree/admin/checkout.yml
- spec/spec_helper.rb
---
Add a basic acceptance test for the extension so you no longer have to run the painful manual testing step before merging a PR. 
---
~~- [ ] Run a sandbox app and verify taxes are being calculated~~
> Add feature spec for checkout

- Gemfile
---
We don't support 2.10 anymore so we should default to the most up to
date version possible.
---
> Update to default solidus version to `solidus@3.1`

- CHANGELOG.md
- bin/sandbox
---
In `solidus@3.0`, the install generator command has been renamed from
`spree:install` to `solidus:install`. This fixes sandbox generation on
`solidus@3` releases.
---
Note that the sandbox app still needs some attention to boot on `solidus@3` due to unregistered custom events.
Fixes #155.
---
> Update sandbox bin stub for `solidus@3`

- CHANGELOG.md
- lib/super_good/solidus_taxjar/api.rb
- spec/super_good/solidus_taxjar/api_spec.rb
---
This pull request simply adds a new TaxJar API endpoint to our API wrapper.
For your convenience, [here's a link to the API documentation](https://developers.taxjar.com/api/reference/?ruby#categories) for the endpoint we're wrapping.
We will use this endpoint in some upcoming work, where we map Solidus tax categories to TaxJar tax categories.
---
N/A
---
> Add tax categories API endpoint wrapper

- app/subscribers/super_good/solidus_taxjar/spree/reporting_subscriber.rb
---
Our CI is failing on Solidus master, so we try to fix it by registering the `shipment_shipped` event. I don't think this event is in the right place yet, so looking for feedback on where others think it belongs.
> Register `shipment_shipped` event

- CHANGELOG.md
- app/controllers/spree/admin/taxjar_settings_controller.rb
- app/views/spree/admin/taxjar_settings/edit.html.erb
- config/routes.rb
- spec/features/spree/admin/taxjar_settings_spec.rb
- spec/fixtures/cassettes/Admin_TaxJar_Settings/Taxjar_settings_tab/Taxjar_API_token_is_set/shows_the_settings_page.yml
- spec/fixtures/cassettes/Admin_TaxJar_Settings/Taxjar_settings_tab/Taxjar_reporting_is_enabled/shows_that_reporting_is_enabled.yml
- spec/requests/spree/admin/taxjar_settings_request_spec.rb
---
Closes #156. The TaxJar settings tab in the Solidus Admin now displays the Nexus regions configured in TaxJar. The user can press the button to sync and cache the Nexus regions via the TaxJar API.  
---
Not applicable; the feature test captures this.
---
Screenshots
---
> Display existing Nexus regions

- app/views/spree/admin/taxjar_settings/edit.html.erb
- spec/features/spree/admin/taxjar_settings_spec.rb
---
The flash message was not displayed when updating the Taxjar configuration due to obscure behavior of `form_with`
---
1. Update the taxjar configuration 
---
- ~~[ ] Update the changelog~~
> Fix flash message not displaying when updating configuration

- lib/super_good/solidus_taxjar/testing_support/factories/address_factory.rb
---
The zip code and state code provided by the default
factory were not a valid pair. This is fine for most tests, but causes
issues when making requests to TaxJar. To fix this, we provide a valid
New York zipcode.
---
> Provide valid state and zip in address factory

- CHANGELOG.md
- app/jobs/super_good/solidus_taxjar/replace_transaction_job.rb
- app/jobs/super_good/solidus_taxjar/report_transaction_job.rb
- app/subscribers/super_good/solidus_taxjar/spree/reporting_subscriber.rb
- lib/super_good/solidus_taxjar/api.rb
- lib/super_good/solidus_taxjar/reporting.rb
- lib/super_good/solidus_taxjar/testing_support/factories/order_transaction_factory.rb
- spec/fixtures/cassettes/SuperGood_SolidusTaxjar_Reporting/_refund_and_create_transaction/when_Taxjar_cannot_create_a_refund_transaction/doesn_t_create_a_new_transaction.yml
- spec/fixtures/cassettes/SuperGood_SolidusTaxjar_Reporting/_refund_and_create_transaction/when_Taxjar_cannot_create_a_refund_transaction/raises_an_error.yml
- spec/jobs/super_good/solidus_taxjar/replace_transaction_job_spec.rb
- spec/jobs/super_good/solidus_taxjar/report_transaction_job_spec.rb
- spec/subscribers/super_good/solidus_taxjar/spree/reporting_subscriber_spec.rb
- spec/super_good/solidus_taxjar/api_spec.rb
- spec/super_good/solidus_taxjar/reporting_spec.rb
---
The goal of this PR is to:
- Subscribe to "order_recalculated" `Spree::Event`s.
- If the `spree_order.total` does not equal the amounts as they are in the
matching TaxJar order transactions (closing #106), we need to refund that
transaction and create a new one with the new amounts (closing #112).
- In all other cases, we currently do nothing with the "order_recalculated"
subscriber.
---
In a sandbox application:
- One easy way to do this would be to check out with two line items and then cancel one of them.
- Order-level adjustments will not work.
---
Screenshots
---
N/A
> Refund and create a new order transaction when an order is recalculated

- CHANGELOG.md
- README.md
- lib/super_good/solidus_taxjar/tax_calculator.rb
- spec/super_good/solidus_taxjar/tax_calculator_spec.rb
---
All tax adjustments need a TaxRate as a source. Previously, we were relying on a user to have a tax rate with the name "Sales Tax" configured. This was an easy to miss configuration step. We should instead create the placeholder `Spree::TaxRate` desired with a descriptive name.
---
1. Calculate some taxes
2. Visit the tax rates page of the admin
---
> Supply a default tax rate

- CHANGELOG.md
- app/controllers/spree/admin/taxjar_settings_controller.rb
- app/models/super_good/solidus_taxjar/transaction_sync_batch.rb
- app/models/super_good/solidus_taxjar/transaction_sync_log.rb
- app/views/spree/admin/taxjar_settings/backfill_transactions.html.erb
- db/migrate/20220405213958_create_transaction_sync_batches.rb
- db/migrate/20220405215225_create_transaction_sync_logs.rb
- lib/super_good/solidus_taxjar/api.rb
- lib/super_good/solidus_taxjar/backfill_transactions.rb
- lib/super_good/solidus_taxjar/reporting.rb
- spec/features/spree/admin/taxjar_settings_spec.rb
- spec/requests/spree/admin/taxjar_settings_request_spec.rb
- spec/super_good/solidus_taxjar/api_spec.rb
- spec/super_good/solidus_taxjar/backfill_transactions_spec.rb
- spec/super_good/solidus_taxjar/reporting_spec.rb
---
1. Verify you have some orders that are ready for back-filling (e.g paid and shipped)
2. Verify the back-fill feature is enabled
3. Request a manual back-fill
4. Open a Rails console on the sandbox app to verify the new models were created (`TransactionSyncBatch` and `TransactionSyncLog`)
---
> Backfill transactions in batches

- CHANGELOG.md
- app/controllers/spree/admin/transaction_sync_batches_controller.rb
- app/models/super_good/solidus_taxjar/transaction_sync_batch.rb
- app/views/spree/admin/transaction_sync_batches/index.html.erb
- config/routes.rb
- lib/super_good/solidus_taxjar/testing_support/factories/transaction_sync_batch_factory.rb
- lib/super_good/solidus_taxjar/testing_support/factories/transaction_sync_log_factory.rb
- spec/features/spree/admin/backfill_transactions_spec.rb
- spec/models/super_good/solidus_taxjar/transaction_sync_batch_spec.rb
---
Show the user the status of transaction sync batches
---
1. Sync some orders to TaxJar
1. Visit `/admin/transaction_sync_batches` and verify a batch with a status is present
---
Screenshots
---
> Show transaction sync batches in user interface

- CHANGELOG.md
- app/models/super_good/solidus_taxjar/order_transaction.rb
- lib/super_good/solidus_taxjar/reporting.rb
- spec/fixtures/cassettes/SuperGood_SolidusTaxjar_Reporting/_refund_and_create_transaction/when_Taxjar_cannot_create_a_refund_transaction/doesn_t_create_a_new_transaction.yml
- spec/fixtures/cassettes/SuperGood_SolidusTaxjar_Reporting/_refund_and_create_transaction/when_Taxjar_cannot_create_a_refund_transaction/raises_an_error.yml
- spec/subscribers/super_good/solidus_taxjar/spree/reporting_subscriber_spec.rb
- spec/super_good/solidus_taxjar/reporting_spec.rb
---
A model existed for refund transactions but was not being created when a refund was reported.
This adds the extra step of creating a refund model after a refund is reported.
---
1. Refund an order
---
> [176] Create refund transaction models when reporting a refund

- CHANGELOG.md
- lib/super_good/solidus_taxjar/reporting.rb
- lib/super_good/solidus_taxjar/testing_support/factories/refund_transaction_factory.rb
- spec/super_good/solidus_taxjar/reporting_spec.rb
---
Reporting a refund to TaxJar consists of two steps
1. Refunding the entire order
2. Reporting a new partial transaction.
We want to ensure that if step 1 succeeds but step 2 fails, that the. `refund_and_create_new_transaction` method can be called again successfully.
---
1. Mimic a partial refund failure (using request hacks? Commented out code?
2. Try to re-report the refund transaction (re-queue the job?)
---
> [176] Handle partial refund failures

- CHANGELOG.md
- lib/super_good/solidus_taxjar/reporting.rb
- spec/super_good/solidus_taxjar/reporting_spec.rb
---
If the entire amount of an order is refunded, and the new order total
is zero, we should not create a subsequent order transaction for zero
dollars after refunding.
We still want to allow some intentionally discounted zero dollar orders
be reported, as the item total affects the nexus and tax
calculations for certain states.
---
1. Refund the entire amount of an order with free shipping 
---
> [176] Don't create new transactions for full refunds

- CHANGELOG.md
- app/jobs/super_good/solidus_taxjar/backfill_transaction_sync_batch_job.rb
- lib/super_good/solidus_taxjar/backfill_transactions.rb
- spec/features/spree/admin/backfill_transactions_spec.rb
- spec/jobs/super_good/solidus_taxjar/backfill_transaction_sync_batch_job_spec.rb
- spec/requests/spree/admin/transaction_sync_batches_request_spec.rb
- spec/super_good/solidus_taxjar/backfill_transactions_spec.rb
---
Transaction backfills have the potential to encompass a large number of orders, so we should execute them asychronously, and direct the user to the in progress batch display page.
---
---
> [150] Asynchronously process transaction backfills

- CHANGELOG.md
- Gemfile
- lib/super_good/solidus_taxjar/testing_support/factories/transaction_sync_log_factory.rb
---
Now that Solidus `master` doesn't include `solidus_frontend` by default
the `common:test_app` rake task modifies extension Gemfile to expand the
meta gem into it's parts. This change commits the diff that we would
otherwise get when running `bin/rake` without an existing dummy app.
We also need to require "rails" again to make the specs pass, else we get
a zeitwerk loading error.
---
> Expand solidus meta gem into dependencies

- CHANGELOG.md
- app/overrides/super_good/solidus_taxjar/spree/order_updater/fire_recalculated_event.rb
- app/overrides/super_good/solidus_taxjar/spree/shipment/fire_shipment_shipped_event.rb
- app/subscribers/super_good/solidus_taxjar/spree/reporting_subscriber.rb
- lib/generators/super_good/solidus_taxjar/install/install_generator.rb
- lib/super_good/engine.rb
- spec/models/spree/order_updater_spec.rb
- spec/models/spree/shipment_spec.rb
- spec/subscribers/super_good/solidus_taxjar/spree/reporting_subscriber_spec.rb
- super_good-solidus_taxjar.gemspec
---
Get tests passing against Solidus `master`.
Update the way we use the Solidus event bus to be forwards compatible with the new Omens bus implementation that is now default in Solidus "=> 3.2.0.alpha" - https://github.com/solidusio/solidus/pull/4342
Additional information on updating to the new event bus implementation - https://github.com/solidusio/solidus/discussions/4380
How do you manually test these changes?
---
1. Test the reporting features against Solidus `master`
1. Run the same tests against Solidus 3.0
---
> Update extension for new Omnes event 🚌 

- CHANGELOG.md
- app/views/spree/admin/transaction_sync_batches/show.html.erb
- spec/requests/spree/admin/transaction_sync_batches_request_spec.rb
---
When an order fails to sync in a transaction backfill, we should render the reason in the UI.
---
1. Backfill a transaction and have it fail
---
Screenshots
---
> [150] Render transaction sync log error message

- CHANGELOG.md
- app/views/spree/admin/taxjar_settings/edit.html.erb
---
This button has been replaced by a tab and is no longer needed
---
1. Visit the taxjar settings page
---
Screenshots
---
**Before**
**After**
> Remove outdated backfill button

- CHANGELOG.md
- app/jobs/super_good/solidus_taxjar/backfill_transaction_sync_batch_job.rb
- app/jobs/super_good/solidus_taxjar/report_transaction_job.rb
- app/models/super_good/solidus_taxjar/transaction_sync_log.rb
- app/overrides/spree/admin/shared/_order_summary/add_taxjar_reported_at.html.erb.deface
- app/overrides/super_good/solidus_taxjar/spree/order_override.rb
- db/migrate/20220912182210_allow_null_transaction_sync_batches_on_logs.rb
- lib/super_good/solidus_taxjar/testing_support/factories/configuration_factory.rb
- spec/features/spree/admin/reporting_to_taxjar_spec.rb
- spec/fixtures/cassettes/Reporting_orders_to_TaxJar/shipping_a_complete_and_paid_order.yml
- spec/jobs/super_good/solidus_taxjar/backfill_transaction_sync_batch_job_spec.rb
- spec/jobs/super_good/solidus_taxjar/report_transaction_job_spec.rb
- spec/requests/spree/admin/order_request_spec.rb
---
We should display the status of the most recent transaction on the status of an ordwr
---
1. Report an order to taxjar
---
Screenshots
---
> [186] Add transaction sync status to orders

- CHANGELOG.md
- app/overrides/spree/admin/orders_controller_override.rb
- app/overrides/spree/admin/shared/_order_submenu/add_taxjar_sync_history_tab.html.erb.deface
- app/views/spree/admin/orders/taxjar_transactions.html.erb
- app/views/spree/admin/shared/_transaction_sync_log_table.html.erb
- app/views/spree/admin/transaction_sync_batches/show.html.erb
- config/routes.rb
- spec/features/spree/admin/backfill_transactions_spec.rb
- spec/requests/spree/admin/order_request_spec.rb
---
Users should be able to easily view the transaction sync history for an order
---
1. Create a order with some taxjar transactions
---
Screenshots
---
> [186] Add page to display taxjar transactions

- spec/super_good/solidus_taxjar/calculator_helper_spec.rb
---
This change fixes the specs against the `master` Solidus branch in preparation for the 1.0 release of this gem.
In a recent change to core, an `after(:build)` hook was added to set the state on the address record for countries which require states. This interferes with the spec setup by ignoring the state attribute we were setting to `nil`. Instead we have moved that to a `before` block so that we can correctly setup the test address to not have a state.
Relevant change upstream - https://github.com/solidusio/solidus/pull/4272
---
1. N/A
---
> Update spec setup to reset state in `before` block

- app/overrides/spree/admin/shared/_configuration_menu.rb
- app/overrides/spree/admin/shared/_order_summary/add_taxjar_reported_at.html.erb.deface
- app/views/spree/admin/taxjar_settings/edit.html.erb
- lib/super_good/solidus_taxjar.rb
- spec/features/spree/admin/backfill_transactions_spec.rb
- spec/features/spree/admin/reporting_to_taxjar_spec.rb
- spec/features/spree/admin/taxjar_settings_spec.rb
- spec/requests/spree/admin/order_request_spec.rb
- spec/super_good/solidus_taxjar_spec.rb
---
The reporting feature is nearly ready for release, and we should remove the UI feature flag in preparation for that.
---
---
> Remove `reporting_ui_enabled` flag from app

- CHANGELOG.md
- lib/super_good/solidus_taxjar.rb
- super_good-solidus_taxjar.gemspec
---
Because our test application includes `solidus_auth_devise`, which depends on `deface`, we didn't realize that we needed to explicitly depend on `deface`. We wrongly thought it would be available to all Solidus stores.
This commit should resolve issue #212.
---
I would like to manually ensure the admin interface is working as intended to ensure we aren't creating problems for end users, like reported in [this comment](https://github.com/SuperGoodSoft/solidus_taxjar/issues/212#issuecomment-1404261063).
---
> Add `deface` as dependency

- README.md
---
Tweak the README before the release of v1.0.
This pull request:
- applies some number formatting, link formatting changes to make the README easier to read as plain text.
- disambiguates between Boomer Digital's and Super Good's `solidus_taxjar` extensions.
- adds a link to the wiki so end user documentation is more discoverable.
- adds a warning about using this extension without a job backend like Sidekiq configured.
---
N/A
---
\* I don't think we need a changelog entry for this.
> Update README in anticipation of v1.0

- CHANGELOG.md
- app/controllers/spree/admin/taxjar_settings_controller.rb
- app/models/super_good/solidus_taxjar/configuration.rb
- app/subscribers/super_good/solidus_taxjar/spree/reporting_subscriber.rb
- lib/super_good/solidus_taxjar/testing_support/factories/configuration_factory.rb
- spec/models/super_good/solidus_taxjar/configuration_spec.rb
- spec/requests/spree/admin/order_request_spec.rb
- spec/requests/spree/admin/taxjar_settings_request_spec.rb
- spec/subscribers/super_good/solidus_taxjar/spree/reporting_subscriber_spec.rb
---
To gracefully handle updates to orders that were never reported at time of purchase.
---
1. Ensure reporting is disabled
1. Complete an order
1. Enable reporting
1. Issue a refund (or some other change that fires `order_recalculated`)
1. Verify the order is not reported
1. Verify there is a sync log with an error
---
> Handle updates to orders that have not been reported

- CHANGELOG.md
- app/subscribers/super_good/solidus_taxjar/spree/reporting_subscriber.rb
- lib/super_good/solidus_taxjar/api_params.rb
- spec/subscribers/super_good/solidus_taxjar/spree/reporting_subscriber_spec.rb
- spec/super_good/solidus_taxjar/api_params_spec.rb
---
Prior to this change, refunds would not trigger the replace transaction job. This is because we compared `order.total` which does not include refunds/reimbursements. We fix this by calling `order.payment_total` instead as it reflects what the customer actually paid. Finally, we have to make the same change in the reporting code.
---
1. Ensure reporting is enabled
1. Complete and ship a new order
1. Refund one or more of the line items
1. Verify the order has been re-reported to TaxJar with the new amount.
---
> Fix reporting for orders with refunds

- .circleci/config.yml
- Gemfile
- bin/sandbox
- spec/spec_helper.rb
---
This is a temporary fix until our PR to `solidus_dev_support` is merged
that allows us to have deeper namespacing of the extension folder
structure.
https://github.com/solidusio/solidus_dev_support/pull/207
This change also updates how we run the CI jobs to separate the current / older versions into separate jobs. With the new Solidus v4.0 release, we still have some work to get the extension passing agains that version as well as `main`. Splitting the jobs allows us to also run each one with a different version of Ruby, which is now required as the `solidus_sample` repo requires Ruby `>= 3.0` for Solidus v4 and `main`.
**NOTE:** There is some overlap in the test runs as `run-specs-solidus-current` will run tests on `v3.2`, `v3.3`, `v3.4` and `v4.0` (on …
> Update how we load factories to be more compatible with Solidus

- CHANGELOG.md
- app/overrides/super_good/solidus_taxjar/spree/shipment/fire_shipment_shipped_event.rb
- app/subscribers/super_good/solidus_taxjar/spree/reporting_subscriber.rb
- lib/super_good/solidus_taxjar.rb
- lib/super_good/solidus_taxjar/reportable.rb
- spec/features/spree/admin/reporting_to_taxjar_spec.rb
- spec/fixtures/cassettes/Reporting_orders_to_TaxJar/shipping_a_complete_and_paid_order.yml
- spec/fixtures/cassettes/Reporting_orders_to_TaxJar/with_an_order_with_invalid_zipcode/retry_of_a_previously_failed_transaction_sync.yml
- spec/spec_helper.rb
- spec/subscribers/super_good/solidus_taxjar/spree/reporting_subscriber_spec.rb
---
- Allow feature specs to run without `--headless` mode
- Add failing feature spec for retrying failed transaction syncs
- Introduce a reportable concern to encapsulate reporting criteria
This work is to address #224. We've started extracting the logic for when to report or replace a transaction in order to achieve the end goal.
**⚠️ NOTE:** We are looking for suggestions of what to name this concern as the reporting subscriber or the controller/views where we will be using this are not necessarily a `Reportable`, but we couldn't come up with anything better.
---
With the Reporting feature enabled: 
1. Ship an order
2. Update an order (w/ refund or additional payment)
3. Update an order completed …
> Manual retry of failed transaction syncs - [Part 1] The Refactor.

- .circleci/config.yml
- CHANGELOG.md
- lib/generators/super_good/solidus_taxjar/install/install_generator.rb
- lib/super_good/engine.rb
- lib/super_good/solidus_taxjar/reportable.rb
- lib/super_good/solidus_taxjar/spree/legacy_reporting_subscriber.rb
- lib/super_good/solidus_taxjar/spree/reporting_subscriber.rb
- spec/features/spree/admin/refund_spec.rb
- spec/subscribers/super_good/solidus_taxjar/spree/reporting_subscriber_spec.rb
---
We want to support Solidus 4.x in time for launching version 1.0 of Solidus TaxJar! Prior to this the extension was using the compatibility layer which allowed us to not have to migrate to the new Omnes API. That however was removed in Solidus 4.x.
This refactor tackles compatibility with the new Omnes event bus by moving our legacy subscriber into a separate module and introducing a new Omnes version!
This change required moving some things around and introducing a new initializer file. We are not set on the naming for that and look for some input on wether having both an `omnes.rb` and `solidus_taxjar_legacy_events.rb` is the best way to do this.
This change depends on #226 being merged first, as that refactor allows us to reduce the duplication of …
> Add support for the new event system in Solidus 4.x

- CHANGELOG.md
- app/models/super_good/solidus_taxjar/order_transaction.rb
- spec/models/super_good/solidus_taxjar/order_transaction_spec.rb
Prior to this commit, we ran into issues retrieving the latest order
transaction as many contained the same transaction date. To fix, we add
secondary sorting ordered by `created_at`.
---
---
1. Do a thing
---
Screenshots
---
> Sort order transactions by created_at

- CHANGELOG.md
- lib/super_good/solidus_taxjar/api_params.rb
- spec/features/spree/admin/refund_spec.rb
- spec/super_good/solidus_taxjar/api_params_spec.rb
Prior to this change, each request to TaxJar sent all line items. We
should exclude line items that have been returned or cancelled so the
total of the line items still adds up to the order's payment total.
> [221] Don't send cancelled or returned line items

- CHANGELOG.md
- app/jobs/super_good/solidus_taxjar/replace_transaction_job.rb
- app/models/super_good/solidus_taxjar/transaction_sync_log.rb
- app/views/spree/admin/shared/_transaction_sync_log_table.html.erb
- db/migrate/20230320211309_add_refund_transaction_to_sync_logs.rb
- spec/features/spree/admin/backfill_transactions_spec.rb
- spec/jobs/super_good/solidus_taxjar/replace_transaction_job_spec.rb
- spec/requests/spree/admin/order_request_spec.rb
- spec/spec_helper.rb
---
We missed the act of creating refund transaction log objects even though the object type exists
This creates sync logs when replacing a transaction on taxjar
---
1. Perform a refund
---
> [221] Create sync logs for replace transaction jobs

- CHANGELOG.md
- app/controllers/spree/admin/taxjar_transactions_controller.rb
- app/overrides/spree/admin/orders_controller_override.rb
- app/overrides/spree/admin/shared/_order_summary/add_taxjar_reported_at.html.erb.deface
- app/overrides/super_good/solidus_taxjar/spree/order_override.rb
- app/views/spree/admin/shared/_transaction_sync_log_table.html.erb
- config/routes.rb
- lib/super_good/solidus_taxjar/reportable.rb
- spec/features/spree/admin/reporting_to_taxjar_spec.rb
- spec/requests/spree/admin/taxjar_transactions_request_spec.rb
- spec/spec_helper.rb
- spec/subscribers/super_good/solidus_taxjar/spree/reporting_subscriber_spec.rb
- spec/support/solidus_events_helper.rb
---
Solidus admin users may need to re-sync an order that failed to sync with TaxJar when it was shipped or recalculated last. This pull request exposes a "Retry" button in the list of transaction sync logs if the latest sync log has an error asociated with it.
---
1. Create and ship an order with two or more line items.
2. Make changes to the order to make it invalid to TaxJar. (For example, make the tax address zipcode totally invalid.)
3. Return one of the line items to force a new order transaction sync with TaxJar.
4. Resolve the issue with the order (i.e. the zipcode).
5. Press the "Retry" button.
---
Screenshots
---
> Let admins manually retry syncing TaxJar transactions

- CHANGELOG.md
- README.md
- spec/spec_helper.rb
This change updates our extension to use the new method provided by `solidus_dev_support` instead of manually requiring the files. This is in line with how `FactoryBot` recommends factories are registered and resolves an issue with our custom override for the `Spree::Address` factory.
Currently the upstream version of `solidus_dev_support` does not handle our use case of having a two folder deep namespace, so this change needs to wait for that to be fixed. We have opened a [PR](https://github.com/solidusio/solidus_dev_support/pull/207) upstream for that to be changed.
**UPDATE:** The PR above has been merged, but we have to wait for an official release for `solidus_dev_support` and upgrade to that before we can merge this.
**UPDATE 2:** `solidus_dev_support` 2.7.0 was released with our …
> Load factories in line with new Solidus conventions

- CHANGELOG.md
- Gemfile
- spec/spec_helper.rb
---
With the latest releases of Selenium, the `webdrivers` gem is no longer compatible. Upstream, `solidus_dev_support` requires `selenium-webdrivers` explicitly, meaning our Webdrivers-specific configuration will cease to work.
This commit prepares us for the future.
---
> Don't depend on the `webdrivers` gem

- CHANGELOG.md
---
This updates the CHANGELOG file to use the format suggested by https://keepachangelog.com and breaks up the changes which will be included in the next release into a few separate categories. It also includes a section at the top titled `Unreleased` where we will add all future changes. That will hopefully help people who use the extension through Rubygems see what will be coming in the next official release.
I am hoping this format help users of the extension easily identify the changes they need to be aware of when upgrading to a new release and also provide us with a framework for how to consistently identify and group related changes.
I looked at the format [solidusio/solidus](https://github.com/solidusio/solidus/blob/master/CHANGELOG.md) uses for their …
> Update CHANGELOG to "Keep a Changelog" format

- CHANGELOG.md
- lib/super_good/solidus_taxjar/spree/legacy_reporting_subscriber.rb
- lib/super_good/solidus_taxjar/spree/reporting_subscriber.rb
---
In a test environment, we discovered that sometimes these jobs would be run before an order's new totals had been persisted by the `Spree::OrderUpdater`. This is an effective workaround, but it is just a workaround.
---
> Add a delay before reporting transactions

- CHANGELOG.md
- README.md
- lib/super_good/solidus_taxjar/version.rb
---
This pull request ties the knot for version 1.0.0 of this extension.
> Release v1.0.0

- README.md
---
Now that we're officially in a stable release, let's show it off. It's
also helpful for users of the extension to see the latest published
version.
---
1. Look at the README
---
Screenshots
---
> Add Gem version badge to README
